apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: test
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: test2
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: example-config
  data:
    key: val
- apiVersion: kubernetes.example.com/v1beta1
  kind: ClusterSpec
  metadata:
    name: cluster-specification
  spec:
    clusterName: kube
- apiVersion: "config.istio.io/v1alpha2"
  kind: stdio
  metadata:
    name: handler
    namespace: istio-system
  spec:
    outputAsJson: true
