---
---
# test with empty and non-k8s yaml
# warning below can come from helm charts
---
WARNING: This chart is deprecated
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test
  labels:
    app: test
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test2
  labels:
    app: test2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-config
  labels:
    app: test
data:
  key: val
---
apiVersion: kubernetes.example.com/v1beta1
kind: ClusterSpec
metadata:
  name: cluster-specification
spec:
  clusterName: kube
---
apiVersion: "config.istio.io/v1alpha2"
kind: stdio
metadata:
  name: handler
  namespace: istio-system
spec:
  outputAsJson: true
