version: 2
project_name: kfilt
before:
  hooks:
    - go mod download
builds:
- id: kfilt
  binary: kfilt
  env:
  - CGO_ENABLED=0
  goos:
  - windows
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`.
  ldflags:
  - -s -w -X github.com/ryane/kfilt/cmd.Version={{.Version}} -X github.com/ryane/kfilt/cmd.GitCommit={{.ShortCommit}}
- id: kubectl-kfilt
  binary: kubectl-kfilt
  env:
  - CGO_ENABLED=0
  goos:
  - windows
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  ldflags:
  - -s -w -X github.com/ryane/kfilt/cmd.Version={{.Version}} -X github.com/ryane/kfilt/cmd.GitCommit={{.ShortCommit}}
universal_binaries:
- id: kfilt
  replace: true
  ids:
  - kfilt
  name_template: "kfilt"
- id: kubectl-kfilt
  replace: true
  ids:
  - kubectl-kfilt
  name_template: "kubectl-kfilt"
archives:
- id: kfilt-binary
  ids:
  - kfilt
  formats:
  - binary
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
- id: kubectl-kfilt-archive
  ids:
  - kubectl-kfilt
  name_template: "kubectl-kfilt_{{.Os}}_{{.Arch}}"
  formats:
  - tar.gz
  - zip
  files:
  - LICENSE
  - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "main"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
dockers:
- image_templates:
  - "ryane/{{.ProjectName}}:{{ .Tag }}-amd64"
  skip_push: false
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - --platform=linux/amd64
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/ryane/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/ryane/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=Apache-2.0
- image_templates:
  - "ryane/{{.ProjectName}}:{{ .Tag }}-arm64v8"
  goarch: arm64
  skip_push: false
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - --platform=linux/arm64/v8
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/ryane/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/ryane/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=Apache-2.0
docker_manifests:
- name_template: "ryane/{{ .ProjectName }}:{{ .Tag }}"
  image_templates:
  - "ryane/{{ .ProjectName }}:{{ .Tag }}-amd64"
  - "ryane/{{ .ProjectName }}:{{ .Tag }}-arm64v8"
- name_template: "ryane/{{ .ProjectName }}:latest"
  image_templates:
  - "ryane/{{ .ProjectName }}:{{ .Tag }}-amd64"
  - "ryane/{{ .ProjectName }}:{{ .Tag }}-arm64v8"
