language: go

go:
- 1.12.x

env:
  global:
  - GO111MODULE=on

install: true

services:
- docker

after_success:
- test -n "$TRAVIS_TAG" && docker login -u="${DOCKER_USERNAME}" -p="$DOCKER_PASSWORD"

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
